"""
    obtain_symmetry_related_hoppings(
        Rs::AbstractVector{V}, 
        brₐ::NewBandRep{D}, 
        brᵦ::NewBandRep{D};
        diagonal_block::Bool = true,
        reverse_hop::Bool = false,
        nonhermitian::Bool = false
    ) --> Vector{HoppingOrbit{D}}

Compute the symmetry-related hopping terms from the points in the WP of `brₐ` to the 
WP of `brᵦ`, displaced by a set of primitive lattice-vector representatives `Rs`.

## Implementation
1. Take a point `a` in the WP of `brₐ` and a point `b` in the WP of `brᵦ`. 
    Compute the displacement vector `δ = b + R - a`, where `R ∈ Rs`, giving the displacement
    vector from `a` (created site) to `b + R` (annihilated site): i.e., `δ` points opposite
    to the hopping direction.
2. If `δ ∈ representatives`, add `δ => (a, b, R)` to the list of hoppings 
    for that representative and continue. Otherwise, search all representatives for one 
    whose list of hoppings contains `δ => (a, b, R)`. If none is found, add `δ` as a new 
    representative and add `δ => (a, b, R)` to its list of hoppings.
3. Take `g ∈ generators`, compute `δ' = g δ` and `(a', b', R') = (g a, g b, g R)`, 
    and repeat step 2.
4. Repeat steps 1–3 for all pairs of points in the WPs of `brₐ` and `brᵦ`.

Additionally, if we are considering a diagonal block (which must be Hermitian or anti-Hermitian),
we check whether orbits that relate `δ` and `-δ` are present; if not, we add them.
"""
function obtain_symmetry_related_hoppings(
    Rs::AbstractVector{V}, # must be specified in the primitive basis
    brₐ::NewBandRep{D},
    brᵦ::NewBandRep{D};
    diagonal_block::Bool = true, # whether to manually add "reversed" hoppings (if true),
    reverse_hop::Bool = false, # if hopping actually goes from a+R→b rather than a→b+R
                               # (used in NONHERMITIAN case, for lower-triangular blocks)
                               # practically just corresponds to flipping signs of `Rs`
    nonhermitian::Bool = false # whether to assume the model is NONHERMITIAN: if false,
                               # we assume HERMITIAN or ANTIHERMITIAN and add & merge
                               # reversed hoppings explicitly; if true (NONHERMITIAN), we
                               # augment every R by -R if diagonal_block is true, to ensure
                               # that we include both "sides" of terms that _would be_
                               # related by Hermitcity (but don't merge them)
) where {V <: Union{AbstractVector{<:Integer}, RVec{D}}} where {D}
    sgnum = num(brₐ)
    num(brᵦ) == sgnum ||
        error("both band representations must belong to the same space group")
    brₐ.timereversal == brᵦ.timereversal ||
        error("input band representations must have identical time-reversal symmetry")

    # we only want to include the Wyckoff positions in the primitive cell - but the default
    # listings from `spacegroup` include operations that are "centering translations";
    # fortunately, the orbit returned for a `NewBandRep` do not include these redundant
    # operations - but is still specified in a conventional basis. So, below, we remove
    # redundant operations from the space group, and also change both the operations and the
    # positions from a conventional to a primitive basis
    cntr = centering(sgnum, D)
    ops = primitivize(spacegroup(sgnum, Val{D}()))
    wpsₐ = primitivize.(orbit(group(brₐ)), cntr)
    wpsᵦ = primitivize.(orbit(group(brᵦ)), cntr)

    # we have defined a structure `HoppingOrbit` to gather the information. It is 
    # structured as:
    # 1. `HoppingOrbit.representatives` will store a representative hopping vector δ
    # 2. `HoppingOrbit.orbit` will store the full orbit of symmetry related hopping 
    #   vector generated by δ: {δᵢ}
    # 3. `HoppingOrbit.hoppings` will store the real coordinates `(a,b,R)` of each 
    #   hopping term associated to each `δᵢ`. Note that maybe several `(a,b,R)` could be 
    #   associated to the same `δᵢ`

    # in the non-Hermitian case, we augment Rs by -Rs if we are in a diagonal block, to
    # ensure we return both "sides" of terms that _would be_ related by Hermiticity;
    # this effectuates a functionality similar to having `reverse_hop` equal to both true
    # _and_ false
    # the reason we need to do this explicitly in the nonhermitian case, is that without
    # hermiticity, we are no longer guaranteed that a hop `a → b+R` links to its conjugate
    # hop `b → a-R`; but a user would usually expect to see both "sides" of such a paired
    # term appear in a returned listing (even though they end up as separate terms); so we
    # augment to ensure this (and the augmenting is only necessary in the diagonal_block,
    # as `reverse_hop` is passed as `true` by `tb_hamiltonian` for non-diagonal blocks)
    if diagonal_block && nonhermitian
        reverse_hop && error("unexpected input combination: `reverse_hop = true`, `nonhermitian = true`, & `diagonal_block = true`")
        Rs = _augment_with_negative_counterparts(Rs)
    end

    h_orbits = HoppingOrbit{D}[]
    for R in Rs
        reverse_hop && (R = -R) # treat as hopping from a+R→b (equivalently, from a→b-R)
        R = RVec{D}(R) # change the type of R for type consistency
        for (qₐ, qᵦ) in Iterators.product(wpsₐ, wpsᵦ)
            qₐ = parent(qₐ) # work with RVec directly rather than Wyckoff Position
            qᵦ = parent(qᵦ)
            δ = qᵦ + R - qₐ # potential representative in next element of `h_orbits`
            maybe_add_hoppings!(h_orbits, δ, qₐ, qᵦ, R, ops)
        end
    end

    # hermiticity/anti-hermiticity could link orbits that spatial symmetries might not have
    # already linked: in particular, if we are in a "diagonal block" of the Hamiltonian,
    # then, for every hopping vector `δ`, we must have a "reversed" counterpart `-δ` in the
    # presence of hermiticity or anti-hermiticity; but those two vectors might have fallen
    # in distinct orbits up this point - if so, we now merge them
    if diagonal_block && !nonhermitian
        add_reversed_orbits!(h_orbits)
    end

    return h_orbits
end

"""
    maybe_add_hoppings!(h_orbits, δ, qₐ, qᵦ, R, ops) --> Vector{HoppingOrbit{D}}

Checks whether a hopping term `δ` is already in the list of representatives. If not, adds it
and its symmetry-related partners. If it is, only the symmetry-related partners are added.
"""
function maybe_add_hoppings!(
    h_orbits,
    δ,
    qₐ,
    qᵦ,
    R,
    ops::AbstractVector{SymOperation{D}},
) where {D}
    δ_idx = findfirst(h_orbits) do h_orbit
        # check if δ is in existing h_orbits
        isapproxin(δ, orbit(h_orbit), nothing, false; atol = VEC_CMP_ATOL)
    end
    if isnothing(δ_idx)
        # if it wasn't already in `h_orbits`, we add it and its symmetry-related partners
        δ_orbit = HoppingOrbit{D}(δ, [δ], [[(qₐ, qᵦ, R)]])
        push!(h_orbits, δ_orbit)
    else # if it was already in `h_orbits`, we only add its symmetry-related partners
        δ_orbit = h_orbits[δ_idx]
    end
    _maybe_add_hoppings!(δ_orbit, δ, qₐ, qᵦ, R, ops)
end

"""
Computes and adds the symmetry related partners of a hopping term `δ` to the `δ_orbit`.

!!! warning
    This function is an internal helper function for `maybe_add_hoppings!` and
    is not part of the public API.
"""
function _maybe_add_hoppings!(
    δ_orbit,
    δ,
    qₐ,
    qᵦ,
    R,
    ops::AbstractVector{SymOperation{D}},
) where {D}
    for g in ops
        _qₐ′ = g * qₐ
        _qᵦ′ = g * (qᵦ + R)
        # _qₐ′ and _qᵦ′ can include a translation part that is a multiple of the lattice
        # translation, so we reduce it to a unit range & keep the translation part separate
        qₐ′ = RVec(reduce_translation_to_unitrange(constant(_qₐ′)), free(_qₐ′))
        qᵦ′ = RVec(reduce_translation_to_unitrange(constant(_qᵦ′)), free(_qᵦ′))
        dₐ = _qₐ′ - qₐ′ # possible lattice translation part of _qₐ′
        dᵦ = _qᵦ′ - qᵦ′ # possible lattice translation part of _qᵦ′

        R′ = dᵦ - dₐ # total lattice translation part of the symmetry-related hopping term δ'
        g_rotation = SymOperation(rotation(g)) # rotation-only part of g
        δ′ = g_rotation * δ # potential symmetry related partner of `δ` to add to `δ_orbit`

        # several sanity checks:
        #   1. R´ is a lattice translation, i.e., it is integer
        #   2. R´ doesn't have any free parameters
        #   3. δ′ = qᵦ′ + R′ - qₐ′
        all(Rᵢ′ -> abs(Rᵢ′ - round(Rᵢ′)) < VEC_CMP_ATOL, constant(R′)) ||
            error("arrived at non-integer lattice translation R′: should be impossible")
        isspecial(R′) || error(
            "arrived at non-special (nonzero free parameters) lattice translation R′: should be impossible",
        )
        isapprox(δ′, qᵦ′ + R′ - qₐ′, nothing, false; atol = VEC_CMP_ATOL) ||
            error("δ′ ≠ qᵦ′ + R′ - qₐ′")

        idx_in_orbit = findfirst(orbit(δ_orbit)) do δ′′
            isapprox(δ′, δ′′, nothing, false; atol = VEC_CMP_ATOL)
        end
        if isnothing(idx_in_orbit)
            # δ′ is not already included in `orbit(δ_orbit)`
            push!(orbit(δ_orbit), δ′)
            push!(δ_orbit.hoppings, [(qₐ′, qᵦ′, R′)])
        else
            # δ′ already in `orbit(δ_orbit)` but hopping term might not be: evaluate
            # `(qₐ′, qᵦ′, R′) ∉ δ_orbit.hoppings[idx_in_orbit]`, w/ approx. comparison
            bool = !any(δ_orbit.hoppings[idx_in_orbit]) do (qₐ′′, qᵦ′′, R′′)
                    isapprox(qₐ′, qₐ′′, nothing, false; atol = VEC_CMP_ATOL) &&
                    isapprox(qᵦ′, qᵦ′′, nothing, false; atol = VEC_CMP_ATOL) &&
                    isapprox(R′, R′′, nothing, false; atol = VEC_CMP_ATOL)
                end
            if bool
                push!(δ_orbit.hoppings[idx_in_orbit], (qₐ′, qᵦ′, R′))
            end
        end
    end
    return δ_orbit
end

"""
    add_reversed_orbits!(h_orbits::Vector{HoppingOrbit{D}}) where {D}

Adds the reversed hopping terms to the hopping orbits in `h_orbits`. The reversed
hopping terms are added to the orbit of the hopping term they are related to; if they are
already present in another orbit, the two orbits are merged.

It is assumed that this functionality will only be called for diagonal blocks.
"""
function add_reversed_orbits!(
    h_orbits::Vector{HoppingOrbit{D}}
) where {D}
    # for any orbit that contains a hopping vector `δ`, we check if its reversed
    # hopping vector `-δ` is also in the orbit; if not, we check if it is in any other
    # orbit to merge them, and, if not, we add it manually to the orbit

    # below, we assume that if, for some δ, no counterpart is found, then no other δ in the
    # orbit has a counterpart, so we can just add it manually

    # determine if `h_orbit`s should be modified
    for (n, h_orbit) in enumerate(h_orbits)
        δs = orbit(h_orbit) # δs in the current orbit

        # check whether the orbit is already "good" (i.e., all δs have a -δ counterpart)
        if all(δ -> isapproxin(-δ, δs, nothing, false; atol = VEC_CMP_ATOL), δs)
            # all δs have a -δ counterpart in the orbit: nominally, the orbit is good as-is
            # there is a corner-case, however, since we must also ensure that for every δ
            # hop a → b + R, the hermitian-partner hop b → a - R exists at -δ; this is not
            # guaranteed automatically, as -δ may have entered the orbit through a symmetry
            # operation that does not necessarily correspond to this "hermitian-partner" 
            # ("reversed hop") relationship; so we check & add any missing "reversed hops"
            hoppings_original = [copy(hops) for hops in h_orbit.hoppings]
            for (idx, δ) in enumerate(δs)
                idx′ = something(findfirst(δs) do δ′
                    isapprox(-δ, δ′, nothing, false; atol = VEC_CMP_ATOL)
                end)
                hops = hoppings_original[idx]
                hops′ = h_orbit.hoppings[idx′]
                for hop in hops
                    (qₐ, qᵦ, R) = hop
                    rev_hop = (qᵦ, qₐ, -R) # reverse hop
                    rev_qₐ, rev_qᵦ, rev_R = rev_hop
                    has_counterpart = any(hops′) do hop′
                        qₐ′, qᵦ′, R′ = hop′
                        (isapprox(rev_qₐ, qₐ′, nothing, false; atol = VEC_CMP_ATOL) &&
                         isapprox(rev_qᵦ, qᵦ′, nothing, false; atol = VEC_CMP_ATOL) &&
                         isapprox(rev_R,  R′,  nothing, false; atol = VEC_CMP_ATOL))
                    end
                    has_counterpart || push!(hops′, rev_hop)
                end
            end
            continue # the orbit is now properly closed: nothing to merge & we continue
        end

        merge_idx = findfirst(@view h_orbits[n+1:end]) do h_orbit′
            isapproxin(-δs[1], orbit(h_orbit′), nothing, false; atol = VEC_CMP_ATOL)
        end
        if !isnothing(merge_idx)
            # at least one δ has a -δ counterpart in another orbit - we need to merge them
            # NB: We assume that if one δ has a -δ counterpart in another orbit, then all
            #     δs in the orbit have a -δ counterpart in the same orbit, so we merge them
            n′ = something(merge_idx) + n
            h_orbit′ = h_orbits[n′]

            # merge the orbits
            append!(h_orbit.orbit, h_orbit′.orbit)
            append!(h_orbit.hoppings, h_orbit′.hoppings)

            # remove the merged orbit
            deleteat!(h_orbits, n′)
            continue
        end
        # we now know that at least some δ doesn't have a -δ counterpart; we assume that
        # this implies that none of the δs have a -δ counterpart, so we need to add them all
        @assert all(δ -> !isapproxin(-δ, δs, nothing, false; atol = VEC_CMP_ATOL), δs)

        # first append the new δs into the orbit
        append!(δs, -δs)

        # add the "reversed" hopping terms: i.e., for every a → b + R, add b + R → a 
        # => -δ = a - (b + R) = a - b - R = b - 2b - R -a + 2a = b + (2a - 2b - R) - a = b + R' - a
        hoppings = h_orbit.hoppings
        hoppings′ = map(hoppings) do hops
            map(hops) do (qₐ, qᵦ, R)
                (qᵦ, qₐ, -R) # reverse the hopping term
            end
        end
        append!(hoppings, hoppings′)
    end
    return h_orbits
end

# for NONHERMITIAN models, hermiticity no longer links a hop `a → b+R` to its conjugate
# hop `b → a-R`; but, in presenting the hopping terms, a user would usually expect to
# see both kinds of hopping families be included if one is - even though they end up as
# separate terms: to ensure this, we add -R to Rs if it is not already in Rs (insert -R
# immediately after R if not already present)
function _augment_with_negative_counterparts(Rs)
    Rs′ = empty!(similar(Rs)) # empty vector with suitable backing size
    for R in Rs
        push!(Rs′, R)
        R_neg = -R
        if !isapproxin(R_neg, Rs; atol = VEC_CMP_ATOL)
            push!(Rs′, R_neg)
        end
    end
    return Rs′
end
# ---------------------------------------------------------------------------- #

# NB: The ordering of `t` is a bit subtle: `t` is a kind of vector-flattened
#        tensor `T`, with the following "indexing convention" for `T`:
#        1. The elements `T[i]` give a vector of hoppings corresponding to the `i`th orbit
#           `δᵢ = h_orbit.orbit[i]`. 
#        2. The elements `T[i][j]` give a vector of hoppings corresponding to the `j`th
#           possible spatial hopping with displacement `δᵢ`, associated with
#           `hᵢⱼ = h_orbit.hoppings[i][j]`.
#           This describes hoppings from site an "origin" `hᵢⱼ[1]` to a "destination"
#           `hᵢⱼ[2] + hᵢⱼ[3]` (where `hᵢⱼ[3]` is an integer "R" translation).
#        3. Finally, `T[i][j][k][m]` is a _single_ hopping term from the `k`-th partner
#           function of `hᵢⱼ[1]` site to the `m`-th partner function of `hᵢⱼ[2]` site.
#        If we are considering a diagonal block, i.e., `brₐ == brᵦ`, then we also have
#        to include the Hermitian or anti-Hermitian counterparts of each hopping term,
#        i.e., for each hopping term from `hᵢⱼ[1]` to `hᵢⱼ[2] + hᵢⱼ[3]`, we also have
#        to include the hopping term from `hᵢⱼ[2]` to `hᵢⱼ[1] - hᵢⱼ[3]`.

# NB: Time-reversal symmetry does NOT imply that if we have a hopping from q to w, we must
#     also have a hopping from w to q. This is a natural first assumption, but a false one.

#     As an example, consider a simple system with two sites, one at [0,0] and another at 
#     [2/3, 1/3]. Let us call `a` an orbital placed at [0,0] and `c` an orbital placed
#     at [2/3, 1/3]. Then, a possible Hamiltonian for first-nearest neighbors is: 
#        `H = \sum_𝐤 (α e^{i2π 𝐤·[-2/3, -1/3]} c_𝐤† a_𝐤 ± h.c.)`
#     where `±` accounts for hermiticity or anti-hermiticity. Let me prove that this
#     Hamiltonian is TRS iff `α` is real. Assume that the time-reversal operator
#     acts on the operators as: 𝒯 c_𝐤 𝒯⁻¹ = c_-𝐤, 𝒯 c_𝐤† 𝒯⁻¹ = c_-𝐤†; and the same for
#     `a_𝐤`. Then, applying the TRS operator to the Hamiltonian, we find:
#        `𝒯 H 𝒯⁻¹ = \sum_𝐤 (α* e^{-i2π 𝐤·[-2/3, -1/3]} c_-𝐤† a_-𝐤 ± h.c.)`
#     Changing the summation variable 𝐤 → -𝐤, we find:
#        `𝒯 H 𝒯⁻¹ = \sum_𝐤 (α* e^{i2π 𝐤·[-2/3, -1/3]} c_𝐤† a_𝐤 ± h.c.)`
#     Then, the only requirement for TRS is that `α = α*`, i.e., `α` is real.

#     This means that, in general, if we have a hopping from q to w, we don't need to
#     have a hopping from w to q.

#     The only terms where we need to consider reversed hoppings are the cases of blocks where
#     hermiticity or anti-hermiticity relates the block to itself: i.e., diagonal blocks. There,
#     if we have a hopping from q to w, we must also have a hopping from w to q, but they both
#     correspond to the same Wyckoff position and site-symmetry irrep, so the former discussion
#     holds.

# ---------------------------------------------------------------------------- #

"""
    OrbitalOrdering(br::NewBandRep{D}) --> OrbitalOrdering{D}

Establishes a canonical, local ordering for the orbitals associated with a band representation
`br`. This is the default ordering used when associating row/column indices in a
tight-binding Hamiltonian block to specific orbitals in the associated band representations.

The canonical orbital ordering is stored in `.ordering`. The `i`th element of `ordering`,
`ordering[i]`, is a `NamedTuple` with two fields:
`wp` and `idx`:
- `wp`: stores a Wyckoff position in the orbit of the Wyckoff position associated to
  `br.wp`.
- `idx`: stores the index of the partner function of the site-symmetry irrep associated to
  `br` at `wp`.

I.e., the `i`th orbital associated with `br` is located at `wp` and transforms as the `idx`th
partner function of the site-symmetry irrep of `br.siteir`.
The total number of orbitals associated to a band representation, and hence the length of
`ordering`, is the product of the site-symmetry irrep dimensionality and the number of sites
in the Wyckoff position orbit.
"""
function OrbitalOrdering(br::NewBandRep{D}) where {D}
    # we only want to include the wyckoff positions in the primitive cell - but the default
    # listings from `spacegroup` include operations that are "centering translations";
    # fortunately, the orbit returned for a `NewBandRep` do not include these redundant
    # operations - but is still specified in a conventional basis. So, below, we remove
    # redundant operations from the space group, and also change both the operations and the
    # positions from a conventional to a primitive basis
    sgnum = num(br)
    cntr = centering(sgnum, D)
    wps = primitivize.(orbit(group(br)), cntr)

    V = length(wps)       # number of Wyckoff positions in orbit
    Q = irdim(br.siteir) # number of orbitals partner functions at each Wyckoff position
    ordering = Vector{@NamedTuple{wp::WyckoffPosition{D}, idx::Int}}(undef, V * Q)
    for i in 1:V
        for k in 1:Q
            ordering[(i-1)*Q+k] = (; wp = wps[i], idx = k)
        end
    end
    return OrbitalOrdering(ordering)
end

"""
    construct_M_matrix(
        h_orbit::HoppingOrbit{D}, br1::NewBandRep{D}, br2::NewBandRep{D},
        [ordering1, ordering2]) 
        --> Array{Int,4}

Construct a set of matrices that encode a Hamiltonian term which resembles the hopping
from EBR `br1` to EBR `br2`.

The encoding is stored as a 4D matrix. Its last two axes correspond to elements of the
Bloch Hamiltonian H(k); its first axis corresponds to `orbit(h_orbit)` and the associated
complex exponentials stored in `v`; and its second axis to the elements of the vector `t`.
That is:

    Hₛₜ(k) = vᵢ(k) Mᵢⱼₛₜ tⱼ

See `devdocs.md` for details.
"""
function construct_M_matrix(
    h_orbit::HoppingOrbit{D},
    br1::NewBandRep{D},
    br2::NewBandRep{D},
    ordering1::OrbitalOrdering{D} = OrbitalOrdering(br1), # canonical orbital orderings for
    ordering2::OrbitalOrdering{D} = OrbitalOrdering(br2),  # `br1` & `br2`, respectively
) where {D}
    V = length(orbit(h_orbit))
    E = length(first(h_orbit.hoppings)) # number of hopping terms per δᵢ (assumed constant for all i)
    foreach(h_orbit.hoppings) do hops
        if length(hops) ≠ E
            error("Unexpectedly had different counts of hoppings across orbit elements")
        end
    end
    Q1, Q2 = irdim(br1.siteir), irdim(br2.siteir)
    Q = Q1 * Q2

    # matrix of matrices that will store the matrix-encoding for each Hamiltonian element
    Mm = zeros(Int, V, V * E * Q, length(ordering1), length(ordering2))

    # fill in the unit-elements of `Mm`
    for α in eachindex(ordering1), β in eachindex(ordering2)
        (q, i) = ordering1[α]
        (w, j) = ordering2[β]
        q = parent(q)
        w = parent(w)

        # assign a 1 to the correct position of WPs times irrep dimensionality
        for (r, hops) in enumerate(h_orbit.hoppings)
            offset0 = (r - 1) * E * Q
            for (x, hop) in enumerate(hops)
                q′, w′ = hop[1], hop[2]
                if (
                    isapprox(q′, q, nothing, false; atol = VEC_CMP_ATOL) &&
                    isapprox(w′, w, nothing, false; atol = VEC_CMP_ATOL)
                )
                    # an "ordinary" hopping, from `q` to `w`
                    offset1 = (x - 1) * Q
                    c = offset0 + offset1 + (j - 1) * Q1 + i
                    Mm[r, c, α, β] = 1
                end
            end
        end
    end

    return Mm
end

"""
    representation_constraints_matrices(
        Mm::AbstractArray{Int,4}, 
        brₐ::NewBandRep{D},
        brᵦ::NewBandRep{D}) --> Vector{Array{ComplexF64,4}}

Build the Q matrix for a particular symmetry operation (or, equivalently, a particular matrix
from the site-symmetry representation), acting on the M matrix.

(ρₐₐ)ᵣₛ Hₛₜ (ρᵦᵦ⁻¹)ₜₗ = (ρₐₐ)ᵣₛ vᵢ Mᵢⱼₛₜ tⱼ (ρᵦᵦ⁻¹)ₜₗ = vᵢ (ρₐₐ)ᵣₛ Mᵢⱼₛₜ (ρᵦᵦ⁻¹)ₜₗ tⱼ,

then we can define: Qᵢⱼᵣₗ = (ρₐₐ)ᵣₛ Mᵢⱼₛₜ (ρᵦᵦ⁻¹)ₜₗ
"""
function representation_constraint_matrices(
    Mm::AbstractArray{Int, 4},
    brₐ::NewBandRep{D},
    brᵦ::NewBandRep{D},
    gens::AbstractVector{SymOperation{D}},
) where {D}
    ρsₐₐ = sgrep_induced_by_siteir_excl_phase.(Ref(brₐ), gens)
    ρsᵦᵦ = sgrep_induced_by_siteir_excl_phase.(Ref(brᵦ), gens)

    Qs = [similar(Mm, ComplexF64) for _ in eachindex(gens)]
    for (n, (ρₐₐ, ρᵦᵦ)) in enumerate(zip(ρsₐₐ, ρsᵦᵦ))
        ρₐₐ = Matrix(ρₐₐ) # since `/` doesn't extend to BlockArrays currently
        ρᵦᵦ = Matrix(ρᵦᵦ) # for type consistency

        # we have constructed the representation matrices such that gΦ(k) = ρᵀ(g)Φ(Rk);
        # then, the Hamiltonian will be transformed due to symmetries as
        # H(g𝐤) = ρₐₐ(g) H(𝐤) ρᵦᵦ⁺(g), this can be translated into the numerical 
        # matrices as
        Q = Qs[n]
        for i in axes(Mm, 1), j in axes(Mm, 2)
            Q[i, j, :, :] .= ρₐₐ * (@view Mm[i, j, :, :]) * ρᵦᵦ'
        end
    end

    return Qs
end

"""
    obtain_basis_free_parameters(
        h_orbit::HoppingOrbit{D},
        brₐ::NewBandRep{D}, 
        brᵦ::NewBandRep{D}, 
       [orderingₐ = OrbitalOrdering(brₐ), 
        orderingᵦ = OrbitalOrdering(brᵦ),
        diagonal_block::Bool = true,
        hermiticity::Hermiticity = HERMITIAN]
        )                            --> Tuple{Array{Int,4}, Vector{Vector{ComplexF64}}}

Obtain the basis of free parameters for the hopping terms between `brₐ` and `brᵦ` 
associated with the hopping orbit `h_orbit`.

## Note

The presence or absence of time-reversal symmetry is inferred implicitly from `brₐ` and `brᵦ`.
"""
function obtain_basis_free_parameters(
    h_orbit::HoppingOrbit{D},
    brₐ::NewBandRep{D},
    brᵦ::NewBandRep{D},
    orderingₐ::OrbitalOrdering{D} = OrbitalOrdering(brₐ),
    orderingᵦ::OrbitalOrdering{D} = OrbitalOrdering(brᵦ),
    diagonal_block::Bool = true,
    hermiticity::Hermiticity = HERMITIAN,
) where {D}
    # obtain the needed representations over the generators of each bandrep
    gensₐ = generators(num(brₐ), SpaceGroup{D})
    gensᵦ = generators(num(brᵦ), SpaceGroup{D})
    @assert gensₐ == gensᵦ # must be from same space group and in same sorting
    brₐ.timereversal == brᵦ.timereversal ||
        error("input band representations must have identical time-reversal symmetry")
    timereversal = brₐ.timereversal

    # cast generators to primitive basis
    cntr = centering(num(brₐ), D)
    gens = cntr ∈ ('P', 'p') ? gensₐ : primitivize.(gensₐ, cntr)

    # encode Hamiltonian as a coefficient matrix sandwiched by exponentials & hopping ampl.
    Mm = construct_M_matrix(h_orbit, brₐ, brᵦ, orderingₐ, orderingᵦ)

    # actual computation
    tₐᵦ_basis_reim = _obtain_basis_free_parameters(
        h_orbit,
        brₐ,
        brᵦ,
        orderingₐ,
        orderingᵦ,
        Mm,
        gens,
        timereversal,
        diagonal_block,
        hermiticity,
    )

    return Mm, tₐᵦ_basis_reim
end

function _obtain_basis_free_parameters(
    h_orbit::HoppingOrbit{D},
    brₐ::NewBandRep{D},
    brᵦ::NewBandRep{D},
    orderingₐ::OrbitalOrdering{D},
    orderingᵦ::OrbitalOrdering{D},
    Mm::Array{Int, 4},
    gens::AbstractVector{SymOperation{D}},
    timereversal::Bool,
    diagonal_block::Bool,
    hermiticity::Hermiticity,
) where {D}
    # encode representation constraints on Hₐᵦ
    Qs = representation_constraint_matrices(Mm, brₐ, brᵦ, gens)

    # encode reciprocal-rotation constraints on Hₐᵦ
    Zs = reciprocal_constraints_matrices(Mm, gens, h_orbit)

    # build an aggregate constraint matrix, over all generators, acting on the hopping
    # coefficient vector tₐᵦ associated with h_orbit
    constraints = _aggregate_constraints(Qs, Zs)
    tₐᵦ_basis_matrix = _retrying_nullspace(constraints; atol = NULLSPACE_ATOL_DEFAULT)

    # at this point, the coefficient-space spanning `tₐᵦ_basis` is implicitly complex; this
    # is conceptually not too nice for a Hamiltonian, and we'd like to work with strictly
    # real coefficients. To that end, we "split" the possible products of such complex
    # coefficients with a complex basis vector into two vectors, where the lower half of
    # each represents the imaginary part of the product. The benefit of this is that it
    # becomes possible to take the complex conjugate of each element "symbolically" by
    # simply multiplying with [1 0; 0 -1] (block matrix). We need to do this anyway if we
    # we have `timereversal = true`, but it's nice to just have a shared representation
    # of the basis vectors, so we do it here as well.

    # If the set of basis vectors obtained from symmetry constraints was empty, there's no
    # point in continuing: we then return early
    isempty(tₐᵦ_basis_matrix) && return Vector{Vector{Float64}}()

    # Details: we split each potentially complex "basis" vector `t = tₐᵦ_basis[i]` into
    # two real vectors `x` and `y`, such that the _real_ span of `x` and `y` is equivalent
    # to the complex span of `t`; the key is that we must interpret the lower halfs of `x`
    # and `y` as representing imaginary numbers. Crucially, this must be kept in mind
    # everywhere that we use a coefficient vector. In particular, we now must always
    # interpret `Mm` as acting like `[Mm Mm]` when meeting a "doubled" basis vector of this
    # kind.
    # Example: we have `t₁ = [im,0]`, `t₂ = [1,im]`, and `tₐᵦ_basis = [t₁,t₂]`, then:
    #    ```
    #    julia> tₐᵦ_basis_split = split_complex.(tₐᵦ_basis)
    #    2-element Vector{Matrix{Int64}}:
    #     [0 -1; 0 0; 1 0; 0 0]
    #     [1 0; 0 -1; 0 1; 1 0]
    #
    #    julia> tₐᵦ_basis_split_matrix = reduce(hcat, tₐᵦ_basis_split)
    #    4×4 Matrix{Int64}:
    #     0  -1  1   0
    #     0   0  0  -1
    #     1   0  0   1
    #     0   0  1   0
    #    ```
    # See `split_complex` for more details on the real/imaginary splitting.
    N = 2size(Mm, 2) # number of elements per `t`-vector, when doubled
    tₐᵦ_basis_reim = split_complex.(eachcol(tₐᵦ_basis_matrix))
    tₐᵦ_basis_reim_matrix =
        reduce(hcat, tₐᵦ_basis_reim; init = Matrix{Float64}(undef, N, 0))

    ## ----------------------------------------------------------------------------------- #
    if timereversal # "add" and "intersect" the associated TRS constraints
        # now we construct the TRS constraints, and then intersect the allowable basis terms
        # of these constraints with those corresponding to the previously computed basis
        tₐᵦ_basis_tr_reim_matrix =
            obtain_basis_free_parameters_TRS(h_orbit, brₐ, brᵦ, orderingₐ, orderingᵦ, Mm)
        tₐᵦ_basis_reim =
            zassenhaus_intersection(tₐᵦ_basis_reim_matrix, tₐᵦ_basis_tr_reim_matrix)
        tₐᵦ_basis_reim_matrix =
            reduce(hcat, tₐᵦ_basis_reim; init = Matrix{Float64}(undef, N, 0))
    end
    isempty(tₐᵦ_basis_reim_matrix) && return Vector{Vector{Float64}}()

    # ------------------------------------------------------------------------------------ #
    # "add" and "intersect" the associated hermiticity constraints if this is a diagonal block
    if diagonal_block && hermiticity ≠ NONHERMITIAN
        antihermitian = hermiticity === ANTIHERMITIAN
        tₐᵦ_basis_herm_reim_matrix = obtain_basis_free_parameters_hermiticity(
            h_orbit,
            brₐ,
            brᵦ,
            antihermitian,
            orderingₐ,
            orderingᵦ,
            Mm,
        )

        tₐᵦ_basis_reim = zassenhaus_intersection(
            tₐᵦ_basis_reim_matrix, tₐᵦ_basis_herm_reim_matrix)
        tₐᵦ_basis_reim_matrix =
            reduce(hcat, tₐᵦ_basis_reim; init = Matrix{Float64}(undef, N, 0))
    end
    isempty(tₐᵦ_basis_reim_matrix) && return Vector{Vector{Float64}}()

    # ------------------------------------------------------------------------------------ #
    # Make sure we have a reasonably pretty-looking basis in the end by sparsifying and
    # dropping near-zero elements explicitly

    # convert null-space to a sparse column form
    tₐᵦ_basis_reim_matrix_form′ = _poormans_sparsification(tₐᵦ_basis_reim_matrix)
    tₐᵦ_basis_reim = [collect(v) for v in eachcol(tₐᵦ_basis_reim_matrix_form′)]

    # prune near-zero elements of basis vectors
    _prune_at_threshold!(tₐᵦ_basis_reim)

    return tₐᵦ_basis_reim
end

# Wrapper around `nullspace` that falls back to QR-iteration SVD if the default
# divide-and-conquer SVD (`gesdd!`) fails with a `LAPACKException`. The fallback is slower
# but unconditionally convergent, and is needed for large constraint matrices arising in
# high-symmetry space groups (e.g., SG 230) on some platforms/LAPACK implementations.
function _retrying_nullspace(
    A;
    atol::Real = 0.0,
    rtol::Real = (min(size(A)...) * eps(real(float(oneunit(eltype(A)))))) * iszero(atol)
)
    try
        return nullspace(A; atol, rtol)
    catch e
        e isa LinearAlgebra.LAPACKException || rethrow(e)
        # the below simply copies the LinearAlgebra implementation of nullspace, with the
        # only adjustment being to pass `alg = LinearAlgebra.QRIteration()` to `svd` to
        # ensure convergence; 
        # TODO: change to `nullspace(A; atol, rtol, alg = LinearAlgebra.QRIteration())`
        #       if https://github.com/JuliaLang/LinearAlgebra.jl/issues/1571 is resolved
        SVD = svd(A; full = true, alg = LinearAlgebra.QRIteration())
        tol = max(atol, SVD.S[1]*rtol)
        indstart = sum(s -> s .> tol, SVD.S) + 1
        return copy((@view SVD.Vt[indstart:end,:])')
    end
end

function _aggregate_constraints(
    Q::AbstractArray{<:Number, 4},
    Z::Union{AbstractArray{<:Number, 4}, <:Number},
    row_atol::Real = 1e-10,
)
    # store constraints in one big vector initially; then we reshape to a matrix after
    constraint_vs = Vector{promote_type(eltype(Q), eltype(Z))}()
    _aggregate_constraints!(constraint_vs, Q, Z, row_atol)

    # return a C×J matrix where each row is a constraint, across C constraints
    J = size(Q, 2) # number of elements per constraint
    return _reshape_aggregate_constraints(constraint_vs, J)
end

function _aggregate_constraints(
    # same as `_aggregate_constraints(Q, V)` but for a vector of Qs and Zs
    Qs::AbstractVector{<:AbstractArray{<:Number, 4}},
    Zs::AbstractVector{<:AbstractArray{<:Number, 4}},
    row_atol::Real = 1e-10,
)
    constraint_vs = Vector{promote_type(eltype(eltype(Qs)), eltype(eltype(Zs)))}()
    for (Q, Z) in zip(Qs, Zs)
        _aggregate_constraints!(constraint_vs, Q, Z, row_atol)
    end
    J = size(first(Qs), 2)
    return _reshape_aggregate_constraints(constraint_vs, J)
end

function _aggregate_constraints!( # modifies `constraint_vs` in place
    constraint_vs::Vector{<:Number},
    Q::AbstractArray{<:Number, 4},
    Z::Union{AbstractArray{<:Number, 4}, <:Number},
    row_atol::Real = 1e-10,
)
    # store constraints in one big vector initially; then we reshape to a matrix after
    J = size(Q, 2)
    c = Vector{eltype(constraint_vs)}(undef, J)

    # avoid repeated recomputation of `norm(c′)` in collinearity check below
    norms = if isempty(constraint_vs)
        Vector{typeof(norm(c))}()
    else # `constraint_vs` is not empty
        map(1:J:length(constraint_vs)) do n
            c′ = @view constraint_vs[n:n+J-1]
            norm(c′)
        end
    end

    # aggregate constraints into `constraint_vs`
    for i in axes(Q, 1), s in axes(Q, 3), t in axes(Q, 4)
        q = @view Q[i, :, s, t]
        z = Z isa Number ? Z : @view Z[i, :, s, t]
        c .= q .- z

        # don't add empty or near-empty constraints
        norm_c = norm(c)
        norm_c < row_atol && continue

        # check whether `c` is collinear w/ any existing constraint; if so, don't add again
        c_dot_c′s = reshape(constraint_vs, J, length(constraint_vs) ÷ J)' * c # elements are `dot(c, c′)`, with `c′` and existing constraint
        collinear = any(zip(c_dot_c′s, norms)) do (c_dot_c′, norm_c′)
            # NB: works also if zip(…) is empty, cf. `any("empty iterator") = false`
            abs(c_dot_c′) ≈ norm_c * norm_c′ # collinear if true
        end
        collinear && continue

        # add the constraint to the list
        append!(constraint_vs, c)
        append!(norms, norm_c)
    end

    return constraint_vs
end

function _reshape_aggregate_constraints(
    constraint_vs::Vector{<:Number}, # vector of inline-concatenated constraints
    J::Int, # number of elements per constraint: ≡ size(Mm,2) = size(Q,2) = size(Z,2)
)
    C = length(constraint_vs) ÷ J # number of constraints
    return permutedims(reshape(constraint_vs, J, C))
end

"""
    reciprocal_constraints_matrices(
        Mm::AbstractArray{Int,4}, 
        gens::AbstractVector{SymOperation{D}}, 
        h_orbit::HoppingOrbit{D}
    ) --> Vector{Array{Int,4}}

Compute the reciprocal constraints matrices for the generators of the SG. This is done by
permuting the rows of the M matrix according to the symmetry operation acting on k-space.
See more details in
`permute_symmetry_related_hoppings_under_symmetry_operation` and `devdocs.md`.
"""
function reciprocal_constraints_matrices(
    Mm::AbstractArray{Int, 4},
    gens::AbstractVector{SymOperation{D}},
    h_orbit::HoppingOrbit{D},
) where {D}
    Zs = Vector{Array{Int, 4}}(undef, length(gens))
    for (i, op) in enumerate(gens)
        Z = similar(Mm)
        Pᵀ = transpose(
            _permute_symmetry_related_hoppings_under_symmetry_operation(h_orbit, op),
        )
        for s in axes(Mm, 3)
            for t in axes(Mm, 4) # vᵀ Ρᵀ Mₛₜ t => vₗ Ρᵀₗᵢ Mᵢⱼₛₜ tⱼ = vₗ Pᵢₗ Mᵢⱼₛₜ tⱼ
                Z[:, :, s, t] .= Pᵀ * @view Mm[:, :, s, t] # Pᵀ M⁽ˢᵗ⁾
            end
        end
        Zs[i] = Z
    end
    return Zs
end

"""
Build the P matrix for a particular symmetry operation acting on k-space, which permutes the
rows of the M matrix.

To obtain the P matrix, we exploit that the action is on exponentials of the type
``exp(2πi𝐤⋅δ)``, and instead act on δ ∈ `h_orbit.orbit` rather than on k. Because of this,
we need to use the inverse of the rotation part of the symmetry operation.

!!! details "Sketch of proof"
    Assume g={R|τ} and `Crystalline` implements gk=(R⁻¹)ᵀk. Then
    (gk)⋅δ = ((R⁻¹)ᵀk)⋅δ + τ = k⋅(R⁻¹)δ.

!!! info
    It is assumed that the operation `op` is provided in a primitive setting.

!!! warning
    This function is an internal helper function for `reciprocal_constraints_matrices` and
    is not part of the public API.
"""
function _permute_symmetry_related_hoppings_under_symmetry_operation(
    h_orbit::HoppingOrbit{D},
    op::SymOperation{D},
) where {D}
    # P is a square matrix that acts as `op` on `v`, i.e., represents ``op ∘ v``, via a
    # matrix-vector product `P*v`. Equivalently, `P` can act on `M` (via its transpose)
    # for expressions of the kind (Pv)ᵀ M … = vᵀ Pᵀ M …
    P = zeros(Int, length(orbit(h_orbit)), length(orbit(h_orbit)))
    for (i, δᵢ) in enumerate(orbit(h_orbit))
        # crystalline implements gk = [R⁻¹]ᵀk. However, since we don't have access to k,
        # being a symbolic variable, we will translate its action into δ. For this,
        # we implement a simple trick: ([R⁻¹]ᵀ k)·r = R⁻¹ᵢⱼ kᵢ rⱼ = k·(R⁻¹ r)
        R⁻¹ = SymOperation(inv(rotation(op))) # rotation-only part of `op`
        δᵢ′ = compose(R⁻¹, δᵢ)
        j = findfirst(orbit(h_orbit)) do δ′′
            isapprox(δᵢ′, δ′′, nothing, false; atol = VEC_CMP_ATOL)
        end
        isnothing(j) &&
            error(lazy"hopping element $δᵢ not closed under $op in $(orbit(h_orbit))")
        P[i, j] = 1
        # since P acts as g v = P v, we have (gv)ᵢ = vⱼ = ∑ₖ Pᵢₖ vₖ so Pᵢₖ = δᵢⱼ
    end
    return P
end

"""
Poor man's "matrix sparsification" via the reduced row echelon form.

!!! warning
    This function is an internal helper function for `obtain_basis_free_parameters` and
    is not part of the public API.
"""
function _poormans_sparsification(
    A::AbstractMatrix{<:Number};
    rref_tol::Union{Nothing, Float64} = SPARSIFICATION_ATOL_DEFAULT,
)
    # following appendix E of the Qsymm paper (https://arxiv.org/abs/1806.08363) [copied
    # over from Neumann.jl] [copied over from MPBUtils.jl]
    if !isnothing(rref_tol)
        # use a relatively low tolerance in `rref` to avoid explosions of errors
        # NB: this optional tolerance argument of `rref!` is undocumented :(
        return transpose(rref!(copy(transpose(A)), rref_tol))
    end
    return transpose(rref(transpose(A)))
end

"""
Prune near-zero elements of vectors in `vs`.

!!! warning
    This function is an internal helper function for `obtain_basis_free_parameters` and
    is not part of the public API.
"""
function _prune_at_threshold!(
    vs::AbstractVector{<:AbstractVector{T}};
    atol::Real = PRUNE_ATOL_DEFAULT,
) where {T <: Complex}
    for v in vs
        for (j, vⱼ) in enumerate(v)
            rⱼ, iⱼ = reim(vⱼ)
            rⱼ′ = ifelse(abs(rⱼ) < atol, zero(real(T)), rⱼ)
            iⱼ′ = ifelse(abs(iⱼ) < atol, zero(real(T)), iⱼ)
            v[j] = T(rⱼ′, iⱼ′)
        end
    end
    return vs
end

function _prune_at_threshold!(
    vs::AbstractVector{<:AbstractVector{T}};
    atol::Real = PRUNE_ATOL_DEFAULT,
) where {T <: Real} # needed for type consistency in TRS implementation
    for v in vs
        for (j, vⱼ) in enumerate(v)
            v[j] = abs(vⱼ) < atol ? zero(T) : vⱼ
        end
    end
    return vs
end

# ---------------------------------------------------------------------------- #

"""
    tb_hamiltonian(
        cbr::CompositeBandRep{D},
        Rs::AbstractVector{Vector{Int}}
        [Sᵛ::Val{S} = Val(HERMITIAN)]
    ) -> TightBindingModel{D, S}

Construct the tight-binding Hamiltonian from a given composite band representation `cbr` and
a set of global translation-representatives `Rs`.

Whether the returned Hamiltonian is Hermitian, anti-Hermitian, or non-Hermitian can be
controlled by passing the optional argument `Sᵛ :: Val{S}` where `S` is an value of the enum
type [`Hermiticity`](@ref), i.e., `HERMITIAN`, `ANTIHERMITIAN`, or `NONHERMITIAN` (default,
`HERMITIAN`).
This choice can also be passed a plain `S` (without a `Val` wrapper) but the call is then
not type-stable.
For `NONHERMITIAN` models, `Rs` is interpreted to also include `-Rs`: this ensures that the
returned hopping terms always feature "both sides" of Hermiticity-related pairs of terms.

The returned [`TightBindingModel`](@ref) will generally feature several terms (iterating to
[`TightBindingTerm`](@ref)s), each representing a tight-binding term that is closed under
the symmetry operations of the underlying space group.
"""
function tb_hamiltonian(
    cbr::CompositeBandRep{D},
    Rs::AbstractVector{<:AbstractVector{Int}} = [zeros(Int, D)], # "global" hopping translation-representatives
    Sᵛ::Val{S} = Val(HERMITIAN),
) where {D, S}
    if any(c -> !isinteger(c) || c < 0, cbr.coefs)
        error("the input composite band representation does not have a symmetric \
               tight-binding model: its expansion in EBRs contain negative or \
               fractional coefficients")
    end
    if !(S isa Hermiticity)
        error(lazy"hermiticity type `S` must be a value of the `Hermiticity` enum: was $S")
    end
    coefs = round.(Int, cbr.coefs)

    # find all bandreps featured in the composite bandrep and build a "repeated" entry list
    brs = Vector{NewBandRep{D}}(undef, sum(coefs))
    idx = 0
    for (i, c) in enumerate(coefs)
        for _ in 1:c
            brs[idx+=1] = cbr.brs[i]
        end
    end

    if any(br -> !iszero(free(position(br))), brs)
        error("free parameters in Wyckoff positions are not supported; any non-special \
               Wyckoff position must have its free parameters pinned to a definite value \
               prior to calling `tb_hamiltonian`: see `pin_free!`")
    end

    # find all families of hoppings between involved band representations: the TB model will
    # be divided into each of these representatives since they will be symmetry independent
    B = length(brs)
    axis = BlockArrays.BlockedOneTo((cumsum(occupation(br) for br in brs)))
    tbs = Vector{TightBindingTerm{D, S}}()
    # We iterate across diagonal blocks, going from the main diagonal and up toward the
    # upper block-diagonals: we do this to get a more natural sorting of the terms in the
    # model, with self-hoppings first, etc. For Hermitian/anti-Hermitian models, we only
    # go over the upper triangular part, with the latter following directly; for
    # non-Hermitian, we just go over all blocks, going along diagonals 0,1,-1,…,B-1,-(B-1)
    for d in _diagonal_indices(B, Sᵛ) # offset from main diagonal (at 0)
        for block_i in _row_indices(B, d, Sᵛ)
            block_j = block_i + d
            br1 = brs[block_i]
            br2 = brs[block_j]
            ordering1 = OrbitalOrdering(br1)
            ordering2 = OrbitalOrdering(br2)
            diagonal_block = d == 0
            reverse_hop = S === NONHERMITIAN ? d<0 : false
            h_orbits = obtain_symmetry_related_hoppings(
                Rs, br1, br2; diagonal_block, reverse_hop, nonhermitian = S===NONHERMITIAN
            )
            for h_orbit in h_orbits
                Mm, t_αβ_basis = obtain_basis_free_parameters(
                    h_orbit,
                    br1,
                    br2,
                    ordering1,
                    ordering2,
                    diagonal_block,
                    S,               #=hermiticity=#
                )
                for t in t_αβ_basis
                    block = TightBindingBlock{D, S}(
                        br1,
                        br2,
                        ordering1,
                        ordering2,
                        h_orbit,
                        Mm,
                        t,
                        diagonal_block
                    )
                    h = TightBindingTerm{D, S}(
                        axis,
                        (block_i, block_j),
                        block,
                        brs,
                    )
                    push!(tbs, h)
                end
            end
        end
    end

    return TightBindingModel(tbs, cbr)
end

# For HERMITIAN/ANTIHERMITIAN: iterate over only non-negative diagonals (negative diagonals
# follow from hermiticity/anti-hermiticity)
_diagonal_indices(B::Int, ::Val{S}) where {S} = 0:B-1
_row_indices(B::Int, d::Int, ::Val{S}) where {S} = 1:B-d
# For NONHERMITIAN: iterate over all diagonal, including positive and negative ones, and do
# it in the order 0, 1, -1, 2, -2, …, B-1, -(B-1)
_diagonal_indices(B::Int, ::Val{NONHERMITIAN}) = (iseven(i) ? -(i÷2) : (i+1)÷2 for i in 0:2(B-1))
_row_indices(B::Int, d::Int, ::Val{NONHERMITIAN}) = d ≥ 0 ? (1:B-d) : (-d+1:B)

function tb_hamiltonian(
    cbr::CompositeBandRep, Rs::AbstractVector{<:AbstractVector{Int}}, S::Hermiticity
) 
    return tb_hamiltonian(cbr, Rs, Val(S))
end
#=
"""
    occupation(br::NewBandRep{D}) --> Int

Counts the number of orbitals in a band representation `br`. This is done by taking 
the multiplicity of the Wyckoff position associated to `br`, dividing it by the 
centering volume fraction (excluding copies due to conventional setting) and 
multiplying it by the dimension of the site irrep.

NB: This is equivalent to `occupation(br)`..!
"""
function occupation(br::NewBandRep{D}) where {D}
    mult = multiplicity(position(br)) # multiplicity in conventional setting
    # we need the Wyckoff multiplicity, excluding conventional-centering copies, so we
    # divide by the the number of centering-translations
    cntr = centering(num(br), D)
    denom = centering_volume_fraction(cntr, Val(D), Val(D))
    mult = div(mult, denom)

    return mult * irdim(br.siteir)
end
=#
