"""
    HoppingOrbit{D}

A structure holding information about symmetry-related spatial hopping vectors.

An orbit includes all symmetry related vectors {δ} = {δ₁, δ₂, …} obtained by applying the
symmetry operations of the underlying space group to a representative vector δ.

For each element of the orbit δᵢ there may be multiple hopping terms, from site `a` to site
`b`, possibly related by a lattice translation `R`. Each such set of possible hopping term
`(a, b, R)` is for each `δᵢ` is stored elements as the `i`th element of the vector
`hoppings`.

## Fields
- `representative :: RVec{D}`: the representative hopping vector δ
- `orbit :: Vector{RVec{D}}`: the δᵢ elements of the orbit generated by δ.
  Generally `orbit[1] == representative`, i.e., `δ₁ = δ`
- `hoppings :: Vector{Vector{NTuple{3,RVec{D}}}}`: the `i`th element gives the possible
  physical hopping terms `(a,b,R)` associated to `orbit[i]`. Multiple physical hopping terms
  may correspond to each element of the orbit. 
  For `(a, b, R) = hoppings[i][j]`, we have `orbit[i] = δᵢ = b + R - a`
"""
struct HoppingOrbit{D}
    representative::RVec{D} # representative hopping vector δ
    orbit::Vector{RVec{D}}  # orbit of the hopping vector {δᵢ …}
    hoppings::Vector{Vector{NTuple{3, RVec{D}}}} # `[(a,b,R), ...]` for every `orbit[i]`
end
representative(s::HoppingOrbit) = s.representative
Crystalline.orbit(s::HoppingOrbit) = s.orbit # extend to avoid clash w/ Crystalline's `orbit`

function Base.:(==)(s1::HoppingOrbit{D}, s2::HoppingOrbit{D}) where {D}
    return (representative(s1) == representative(s2) && orbit(s1) == orbit(s2) &&
            s1.hoppings == s2.hoppings)
end
Base.:(==)(::HoppingOrbit, ::HoppingOrbit) = false # different dimensions (less specific)

# ---------------------------------------------------------------------------------------- #
# constructor defined in /src/tightbinding.jl

struct OrbitalOrdering{D} <: AbstractVector{@NamedTuple{wp::WyckoffPosition{D}, idx::Int}}
    ordering::Vector{@NamedTuple{wp::WyckoffPosition{D}, idx::Int}}
end
Base.getindex(o::OrbitalOrdering, i::Int) = o.ordering[i]
Base.size(o::OrbitalOrdering) = size(o.ordering)
Base.setindex!(::OrbitalOrdering, v, i::Int) = error("setindex! is not supported")
Base.IndexStyle(::Type{OrbitalOrdering}) = IndexLinear()
Base.iterate(o::OrbitalOrdering) = iterate(o.ordering)
Base.iterate(o::OrbitalOrdering, i) = iterate(o.ordering, i)

# ---------------------------------------------------------------------------------------- #

"""
    TightBindingElementString

A structure for pretty-printing tight-binding matrix elements.

## Fields
- `s :: String`: the string representing the tight-binding matrix element
- `active :: Bool`: whether the element belongs to an "active" block - i.e., one we want to
  highlight (then shown in blue).
"""
struct TightBindingElementString
    s::String
    active::Bool
end
function Base.show(io::IO, tbe_str::TightBindingElementString)
    s = tbe_str.s
    color = (
        tbe_str.active ? (s == "0" ? :normal : :blue) : (s == "0" ? :light_black : :normal)
    )
    printstyled(io, s; color)
end

"""
    TightBindingBlock{D, S}

A structure for storing information about a matrix block of a tight-binding Hamiltonian of
dimensionality `D` and [`Hermiticity`](@ref) `S`.

A block represents a hopping term from band representation `br1` to `br2` (and possibly also
from `br2` to `br1` if `diagonal_block = false` and `S` is not `NONHERMITIAN`).

## Fields
- `br1 :: NewBandRep{D}`: first band representation
- `br2 :: NewBandRep{D}`: second band representation
- `ordering1 :: OrbitalOrdering{D}`: ordering of the orbitals in `br1`
- `ordering2 :: OrbitalOrdering{D}`: ordering of the orbitals in `br2`
- `h_orbit :: HoppingOrbit{D}`: hopping orbit associated to the block
- `Mm :: Array{Int,4}`: matrix codifying Hamiltonian
- `t :: Vector{Float64}`: a basis vector, stored in re/im-doubled format
- `MmtC :: Array{ComplexF64, 3}`: pre-contracted matrix `Mm` with "complexified" `t`.
- `diagonal_block :: Bool`: whether this is a diagonal block in the overall Hamiltonian.
"""

struct TightBindingBlock{D, S} <: AbstractMatrix{TightBindingElementString}
    br1::NewBandRep{D}
    br2::NewBandRep{D}
    ordering1::OrbitalOrdering{D}
    ordering2::OrbitalOrdering{D}
    h_orbit::HoppingOrbit{D}
    Mm::Array{Int, 4}
    t::Vector{Float64}
    MmtC::Array{ComplexF64, 3} # MmtC[:,i,j] = M[:,:,i,j] * complex.(t[1:N], t[N+1:end])
    # we include `MmtC` as an optimization: we want `Mm` for structural information (e.g.
    # for plotting), but for computing the block matrix elements, we actually only need
    # the (column-)contracted matrix `MmtC` (see `evaluate_tight_binding_term!`)
    diagonal_block::Bool # whether this is a diagonal block in the overall Hamiltonian
end
Base.size(tbb::TightBindingBlock) = (size(tbb.Mm, 3), size(tbb.Mm, 4))
function TightBindingBlock{D, S}(
    br1::NewBandRep{D},
    br2::NewBandRep{D},
    ordering1::OrbitalOrdering{D},
    ordering2::OrbitalOrdering{D},
    h_orbit::HoppingOrbit{D},
    Mm::AbstractArray{<:Integer, 4},
    t::AbstractVector{<:Real},
    diagonal_block::Bool
) where {D, S}
    Nᵗ = length(t) ÷ 2
    tC = complex.((@view t[1:Nᵗ]), (@view t[Nᵗ+1:end]))
    MmtC = Array{ComplexF64}(undef, size(Mm, 1), size(Mm, 3), size(Mm, 4))
    for i in axes(Mm, 3), j in axes(Mm, 4)
        MmtC[:, i, j] = (@view Mm[:, :, i, j]) * tC
    end
    tbb = TightBindingBlock{D, S}(
        br1, 
        br2, 
        ordering1, 
        ordering2, 
        h_orbit, 
        Mm, 
        t, 
        MmtC, 
        diagonal_block
    )
    return tbb
end

"""
    Hermiticity (enum)

Enum-type (base type `UInt8`) describing the properties of a Hamiltonian under
Hermitian conjugation. Values:
- `HERMITIAN`: H† = H.
- `ANTIHERMITIAN`: H† = -H.
- `NONHERMITIAN`: H† unrelated to H.
"""
@enum Hermiticity::UInt8 begin
    HERMITIAN
    ANTIHERMITIAN
    NONHERMITIAN
end


"""
    TightBindingTerm{D, S}

A single term a tight-binding Hamiltonian, representing a single block or a
hermiticity-related pair of blocks of the Hamiltonian matrix.

## Fields
- `axis :: BlockedOneTo{Int, Vector{Int}}`: the blocked axis of the term, encoding the
  global row/column indices all blocks in the full Hamiltonian matrix.
- `block_ij :: NTuple{2, Int}`: the indices of considered term in the blocked axes; i.e.,
  `axis[block_ij...]` gives the global row/column indices of the "key" block represented by
  the term. If `S` is `NONHERMITIAN` or the term is diagonal, the key block is the only
  block represented by the term; otherwise, the term also represents the hermiticity-related
  block, whose global coordinates are `axis[reverse(block_ij)...]`.
- `block :: TightBindingBlock{D, S}`: the `TightBindingBlock` associated to the key block.
- `brs :: Vector{NewBandRep{D}}`: the set of band representations involved in the
  Hamiltonian; each element corresponds to a block-index in `axis`, such that `axis[i, j]`
  gives the (block of) hopping amplitudes from `brs[j]` to `brs[i]`.
"""
struct TightBindingTerm{D, S} <: AbstractBlockMatrix{TightBindingElementString}
    axis::BlockedOneTo{Int, Vector{Int}}
    block_ij::NTuple{2, Int}
    block::TightBindingBlock{D, S}
    brs::Vector{NewBandRep{D}}
end

hermiticity(::TightBindingTerm{D, S}) where {D, S} = S

Base.axes(H::TightBindingTerm) = (H.axis, H.axis)
function Base.axes(H::TightBindingTerm, d::Int)
    d > 2 ? Base.BlockedOneTo([1]) :
    d > 0 ? H.axis : error("dimensionality must be greater than 1")
end
Base.size(H::TightBindingTerm) = (N = last(H.axis); (N, N))

function Base.getindex(H::TightBindingTerm{D, S}, i::Int, j::Int) where {D, S}
    N = size(H, 1)
    @boundscheck 1 ≤ i ≤ N && 1 ≤ j ≤ N || error(BoundsError(H, (i, j)))
    tmp = BlockArrays.findblockindex(H.axis, i)
    block_i = only(tmp.I)
    local_i = only(tmp.α)
    tmp = BlockArrays.findblockindex(H.axis, j)
    block_j = only(tmp.I)
    local_j = only(tmp.α)
    if H.block_ij == (block_i, block_j)
        return _getindex(H.block, local_i, local_j)
    elseif S !== NONHERMITIAN && H.block_ij == (block_j, block_i) # hermiticity-related block
        return _getindex(H.block, local_j, local_i, #=conjugate=# true)
    else # not a stored block
        return TightBindingElementString("0", #=active=# false)
    end
end

function _getindex(
    tbb::TightBindingBlock{D, S},
    i::Int,
    j::Int,
    conjugate::Bool = false
) where {D, S}  
    @boundscheck 1 ≤ i ≤ size(tbb.Mm, 3) && 1 ≤ j ≤ size(tbb.Mm, 4) ||
                 error(BoundsError(tbb, (i, j)))

    io = IOBuffer()
    MⁱʲtC = tbb.MmtC[:, i, j] # = `tbb.Mm[:,:,i,j] * "complexified"(tbb.t)`
    if all(v -> abs(v) < SPARSIFICATION_ATOL_DEFAULT, MⁱʲtC)
        return TightBindingElementString("0", #=active=# true)
    end

    first = true
    for (n, v) in enumerate(MⁱʲtC)
        abs(v) < SPARSIFICATION_ATOL_DEFAULT && continue
        vᴿ, vᴵ = reim(v)
        if conjugate
            if S === ANTIHERMITIAN
                # getting a block related to the stored one by antihermiticity; conjugate
                # _and_ negate: vᴵ is invariant, but vᴿ swaps: cf. -(conj(v)) = -vᴿ+ivᴵ
                vᴿ = -vᴿ
            else # HERMITIAN or NONHERMITIAN
                vᴵ = -vᴵ # just complex conjugate → vᴵ changes sign: conj(v) = vᴿ-ivᴵ
            end
        end

        vᴿ′, vᴿ_str = _stringify_real(vᴿ)
        vᴵ′, vᴵ_str = _stringify_real(vᴵ)
        if vᴵ′ == 0     # strictly real
            v_str = isone(abs(vᴿ′)) ? "" : lstrip(vᴿ_str, ('-', '+'))
            v_str = (vᴿ′ < 0 ? "-" : (first ? "" : "+")) * v_str
        elseif vᴿ′ == 0 # strictly imaginary
            v_str = isone(abs(vᴵ′)) ? "" : lstrip(vᴵ_str, ('-', '+'))
            v_str = (vᴵ′ < 0 ? "-" : (first ? "" : "+")) * v_str * "i"
        else            # complex
            v_str =
                (first ? "" : " + ") *
                "(" *
                _complex_as_compact_string(complex(vᴿ′, vᴵ′)) *
                ")"
        end
        print(io, v_str)

        δ = tbb.h_orbit.orbit[n]
        if !iszero(δ) # print the exponential: our notation is 𝕖(δ) ≡ exp(2πi𝐤⋅δ)
            print(io, "𝕖(")
            # TODO: could do a little better here, since we know that `-δ` is in the orbit?
            conjugate && print(io, "-")
            print(io, "δ", Crystalline.subscriptify(string(n)), ")")
        else
            print(io, "1")
        end

        first = false
    end

    s = String(take!(io))
    return TightBindingElementString(s, #=active=# true)
end

function Base.getindex(tbb::TightBindingBlock, i::Int, j::Int)
    return _getindex(tbb, i, j, #=conjugate=# false)
end

Base.setindex!(::TightBindingBlock, v, ij...) = error("setindex! is not supported")

# pretty-printing of scalars

function _stringify_real(c::Real; digits::Int = 3)
    c′ = round(c; digits)
    isinteger(c′) && return c′, string(Int(c′))
    return c′, string(c′)
end

function _complex_as_compact_string(c::Complex) # usual string(::Complex) has spaces; 
    # avoid that
    io = IOBuffer()
    print(io, real(c), Crystalline.signaschar(imag(c)), abs(imag(c)), "i")
    return String(take!(io))
end

# ---------------------------------------------------------------------------------------- #

"""
    TightBindingModel{D, S}

A structure storing a list of `TightBindingTerm{D, S}`s. Each term is assumed to associated
with an identical list of EBRs.

To associate a set of coefficients to each term, see
[`ParameterizedTightBindingModel`](@ref), which also allows evaluation at specific momenta.

## Fields

- `terms :: Vector{TightBindingTerm{D, S}}`: a vector of `TightBindingTerm{D}`s, each of
   which represents a block (or conjugated pairs of blocks) of the Hamiltonian matrix.
   Associates to a `D`-dimensional lattice and with Hermitian-conjugation symmetry `S`.
- `cbr :: CompositeBandRep{D}`: the composite band representation associated to the model.
- `positions :: Vector{DirectPoint{D}}`: a vector of positions, specified in the lattice
  basis, associated to each orbital of the model.
- `N :: Int`: the total number of orbitals in the model, i.e., the size of the Hamiltonian
  matrix associated to each element of `terms`.
"""
struct TightBindingModel{D, S} <: AbstractVector{TightBindingTerm{D, S}}
    terms::Vector{TightBindingTerm{D, S}}
    cbr::CompositeBandRep{D} # band representation associated to the model
    positions::Vector{DirectPoint{D}} # positions associated to each orbital
    N::Int # total number of orbitals, i.e., matrix size
end
Base.size(tbm::TightBindingModel) = (length(tbm.terms),)
Base.getindex(tbm::TightBindingModel, i::Int) = tbm.terms[i]
Base.setindex!(tbm::TightBindingModel, v, i::Int) = setindex!(tbm.terms, v, i)
Base.IndexStyle(::Type{TightBindingModel}) = IndexLinear()
function Base.similar( # extending this makes e.g. `tbm[1:3]` & `vcat` work
    tbm::TightBindingModel{D, S},
    ::Type{TightBindingTerm{D, S}}, # element_type
    dims::Tuple{Int} = size(tbm),
) where {D, S}
    similar_terms = similar(tbm.terms, TightBindingTerm{D, S}, dims)
    return TightBindingModel{D, S}(similar_terms, tbm.cbr, tbm.positions, tbm.N)
end

"""
    hermiticity(tbt::TightBindingTerm)                -> Hermiticity
    hermiticity(tbm::TightBindingModel)               -> Hermiticity
    hermiticity(ptbm::ParameterizedTightBindingModel) -> Hermiticity

Return the [`Hermiticity`](@ref) of the input.

If the input features multiple terms (i.e., is a sum of terms, as in a `TightBindingModel`),
it is assumed that all terms have identical hermiticity.
"""
hermiticity(::TightBindingModel{D, S}) where {D, S} = S
orbital_positions(tbm::TightBindingModel) = tbm.positions
Crystalline.CompositeBandRep(tbm::TightBindingModel) = tbm.cbr

function TightBindingModel(
    terms::Vector{TightBindingTerm{D, S}},
    cbr::CompositeBandRep{D},
) where {D, S}
    positions = orbital_positions(cbr)
    length(terms) == 0 && return TightBindingModel{D, S}(terms, cbr, positions, 0)
    N = last(first(terms).axis)
    return TightBindingModel{D, S}(terms, cbr, positions, N)
end
function (tbm::TightBindingModel{D, S})(cs::AbstractVector{<:Real}) where {D, S}
    return ParameterizedTightBindingModel{D, S}(tbm, cs)
end

# ---------------------------------------------------------------------------------------- #

# union-type for valid k-point input; defined to avoid repeating this everywhere
const ReciprocalPointLike{D} =
    Union{AbstractVector{<:Real}, NTuple{D, <:Real}, ReciprocalPoint{D}}

# ---------------------------------------------------------------------------------------- #

"""
    ParameterizedTightBindingModel{D, S}

A coefficient-parameterized tight-binding model, that can be used as a functor for
evaluation at input momenta `k`.

## Fields

- `tbm :: TightBindingModel{D}`: A tight-binding model, consisting of a set of a list of
  `TightBindingTerm{D}`s.
- `cs :: Vector{Float64}`: A vector of coefficients, each associated to a corresponding
  element of `tbm`.
- `scratch :: Matrix{ComplexF64}`: A scratch space for evaluating the Hamiltonian matrix at
  at specific momenta. This is a `N×N` matrix, where `N` is the number of orbitals in `tbm`
  (i.e., `tbm.N`). The scratch space is instantiated automatically on construction.

## Functor over momenta

A `ParameterizedTightBindingModel` `ptbm` can be be evaluated at any ´D`-dimensional
momentum `k` by using `ptbm` as a functor. That is, `ptbm(k)` returns a numerical
representation of the Hamiltonian matrix for `ptbm` evaluated at momentum `k`.`
"""
struct ParameterizedTightBindingModel{D, S}
    tbm::TightBindingModel{D, S}
    cs::Vector{Float64} # coefficients of the tight-binding model
    scratch::Matrix{ComplexF64} # scratch space for evaluation
    # inner constructor w/ checks & conversion of input
    function ParameterizedTightBindingModel{D, S}(
        tbm::TightBindingModel{D, S},
        cs::AbstractVector{<:Real},
        scratch::Matrix{ComplexF64} = Matrix{ComplexF64}(undef, tbm.N, tbm.N),
    ) where {D, S}
        length(tbm.terms) ≠ length(cs) && _throw_term_coef_length_mismatch(tbm.terms, cs)
        size(scratch) ≠ (tbm.N, tbm.N) && _throw_scratch_size_mismatch(scratch, tbm.N)
        return new{D, S}(tbm, convert(Vector{Float64}, cs), scratch)
    end
end
@noinline function _throw_scratch_size_mismatch(scratch, N)
    s_scratch = size(scratch)
    error(DimensionMismatch("scratch size ($s_scratch) does not match model size ($N, $N)"))
end
@noinline function _throw_term_coef_length_mismatch(terms, cs)
    Nt = length(terms)
    Nc = length(cs)
    error("number of coefficients ($Nc) does not match number of model terms ($Nt)")
end

hermiticity(::ParameterizedTightBindingModel{D, S}) where {D, S} = S
orbital_positions(ptbm::ParameterizedTightBindingModel) = ptbm.tbm.positions
Crystalline.CompositeBandRep(ptbm::ParameterizedTightBindingModel) = ptbm.tbm.cbr

function (ptbm::ParameterizedTightBindingModel{D})(
    k::ReciprocalPointLike{D},
    scratch::Matrix{ComplexF64} = ptbm.scratch,
) where {D}
    if length(k) ≠ D
        error("momentum `k` must be a $D-dimensional vector to match the model dimension")
    end
    tbm = ptbm.tbm
    size(scratch) ≠ (tbm.N, tbm.N) && _throw_scratch_size_mismatch(scratch, tbm.N)

    H = scratch # grab & reset scratch space for evaluating Hamiltonian matrix
    fill!(H, 0.0)

    # evaluate each block of the Hamiltonian terms, multiply by coefficients, & store in `H`
    for (tbt, c) in zip(tbm.terms, ptbm.cs)
        evaluate_tight_binding_term!(tbt, k, c, H) # modifies `H` in-place
    end

    return H
end

"""
    evaluate_tight_binding_term!(tbt::TightBindingTerm, k, [c, H])

Evaluate the tight-binding term `tbt` at momentum `k`, possibly multiplied by a scalar
coefficient `c` (unity if omitted). The term is _added_ into the scratch space matrix `H`;
if `H` is not provided, it is initialized as a zero matrix of the appropriate size.

The function returns the modified `H` matrix.
    
## Note
The two-argument form of the function, i.e., returning the value of `tbt` at `k`, can be
more simply achieved via `tbt(k)`.
"""
function evaluate_tight_binding_term!(
    tbt::TightBindingTerm{D, S},
    k::ReciprocalPointLike{D},
    c::Union{Nothing, <:Number} = nothing,
    H::Matrix{ComplexF64} = zeros(ComplexF64, size(tbt)),
) where {D, S}
    block = tbt.block
    block_i, block_j = tbt.block_ij
    is = tbt.axis[Block(block_i)] # global row indices
    js = tbt.axis[Block(block_j)] # global col indices
    MmtC = block.MmtC # contracted product of `Mm` and (complexified) `t`

    # NB: ↓ one more case of assuming no free parameters in `δ`
    v_conj = cispi.(dot.(Ref(-2 .* k), constant.(orbit(block.h_orbit))))
    # NB: ↑ this is `v` conjugated: we do this because the `dot`-product below conjugates
    #     its first argument; so by conjugating twice we get the unconjugated result.
    # NB: ↑ each term in the Hamiltonian is associated to an annihilation+creation operator
    #     pair `aᵢ† aⱼ`. Since we use Convention 1 for the Fourier transform, we have
    #     aᵢ† = √N⁻¹ ∑ₖ e^{-ik·(tᵢ + rᵢ)} aₖ†, such that each term will be multiplied by a
    #     phase e^{ik·δᵢⱼ} with δᵢⱼ ≡ Rᵢⱼ + rᵢ - rⱼ, i.e., the hopping vector in the orbit;
    #     this is what `orbit(block.h_orbit)` gives us above
    for (local_i, i) in enumerate(is)
        for (local_j, j) in enumerate(js)
            Hᵢⱼ = @inbounds dot(v_conj, @view MmtC[:, local_i, local_j])
            isnothing(c) || (Hᵢⱼ *= c) # multiply by coefficient if provided
            H[i, j] += Hᵢⱼ
            if S !== NONHERMITIAN && i ≠ j # add off-diagonal hermiticity-related block
                H[j, i] += S === ANTIHERMITIAN ? -conj(Hᵢⱼ) : conj(Hᵢⱼ)
            end
        end
    end

    return H
end

function (tbt::TightBindingTerm{D})(k::ReciprocalPointLike{D}) where {D}
    if length(k) ≠ D
        error("momentum `k` must be a $D-dimensional vector to match the model dimension")
    end
    return evaluate_tight_binding_term!(tbt, k)
end

function solve(
    ptbm::ParameterizedTightBindingModel{D, S},
    k::ReciprocalPointLike{D};
    bloch_phase::Union{Val{true}, Val{false}} = Val(false),
    eigen_kws...,
) where {D, S}
    length(k) == D || error("dimension mismatch")
    _H = ptbm(k)
    H = S == HERMITIAN ? Hermitian(_H) : _H
    es, vs = eigen!(H; eigen_kws...)
    if bloch_phase === Val(true)
        Θₖ = reciprocal_translation_phase(orbital_positions(ptbm), k)
        # NB: we start in convention 1 for the returned eigenfunctions `vs`, so the Bloch 
        # periodic functions ψ(rᵢ + t) are e^{ik·(t+rᵢ)} * vᵢ (with vᵢ denoting the ith element
        # a vector `v` in `vs`, corresponding to the ith position rᵢ); this then returns ψ(rᵢ)
        # This is equivalent to convert the eigenfunctions to the convention 2 Fourier transform,
        # see Appendix A in `docs/scr/theory.md`.
        vs = Θₖ' * vs # add Bloch phases
        return es, vs
    else
        return es, vs
    end
end

function solve(ptbm::ParameterizedTightBindingModel{D}, k::KVec{D}; kws...) where D
    isspecial(k) || error("input k-point has free parameters, i.e., is not definite")
    solve(ptbm, constant(k); kws...)
end

# ---------------------------------------------------------------------------------------- #
#=
struct NonHermitianTightBindingModel{D}
    tbm_h::TightBindingModel{D, HERMITIAN}
    tbm_a::TightBindingModel{D, ANTIHERMITIAN}
end
=#